apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: emr-service-api
    newName: emr-service-api
    newTag: sha-291a8688b263dbc9927d3b54a3d2326f7fdcfea0
