apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: emr-service-api
    newName: emr-service-api
    newTag: sha-b1b9afb5c86263d0d3aa0668867053b3c2d4132f
  - name: emr-service-frontend
    newName: emr-service-frontend
    newTag: sha-b1b9afb5c86263d0d3aa0668867053b3c2d4132f
