apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: emr-service-api
    newName: emr-service-api
    newTag: sha-561a2e6b4e5da19f0c4ce637784e49cee930e0c8
  - name: emr-service-frontend
    newName: emr-service-frontend
    newTag: sha-bootstrap