apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: emr
  namespace: argocd
spec:
  description: EMR production workloads on the local minikube cluster.
  sourceRepos:
    - git://host.minikube.internal/spda-project.git
  destinations:
    - namespace: emr
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
