apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emr
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - my-emr.duckdns.org
      secretName: emr-tls
  rules:
    - host: my-emr.duckdns.org
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
